# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 23b8396e4a074a0c0ab6154547ed2307eba40f6a1bf566dce4940e2feb00ccb5fe7c93a1853b02149c9e68469048afebcd9fa4b913d2dc0676fd125703543d33

test:
  secret_key_base: 1505df0625f2739f6dbde479d432f163386bfb62d1fe972c7988f0dbcf9b15729cf240ab6f49c4e97691b2b710b3d952f07b970da18bb17df28b5a068d2c8973

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
